In [3]:
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


In [4]:

df = pd.read_csv("employees.csv")

ages = np.array(df['age'])
salaries = np.array(df['salary'])

print(ages)
print(salaries)

print(ages.dtype)
print(ages.ndim)
print(ages.shape)
print(ages.size)


print(salaries.dtype)
print(salaries.ndim)
print(salaries.shape)
print(salaries.size)



[56 46 32 25 38 56 36 40 28 28]
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
int64
1
(10,)
10
int64
1
(10,)
10


In [5]:
#Using the salaries array, found and printed the highest and lowest salary values.
#Also, calculated and printed the average salary and age using NumPy functions.
highest_salary = np.max(salaries)
lowest_salary = np.min(salaries)
average_salary = np.mean(salaries)
print("Highest salary: ",highest_salary)
print("Lowest salary: ",lowest_salary)
average_age = np.mean(ages)
print("Average salary: ",average_salary)
print("Average age: ",average_age)

Highest salary:  89735
Lowest salary:  30769
Average salary:  57446.9
Average age:  38.5


In [ ]:
#From the ages array, filtered and printed all ages greater than 30 using a boolean condition.
#Then counted and printed how many employees are older than 30.
ages_over_30 = ages[ages > 30]
count_over_30 = np.sum(ages > 30)
print("Ages greater than 30:", ages_over_30)
print("Number of employees older than 30:", count_over_30)

Ages greater than 30: [56 46 32 38 56 36 40]
Number of employees older than 30: 7


In [ ]:
#Created a new NumPy array that increases every employee’s age by 5 years. Printed the new updated ages array.
updated_ages = ages + 5
print(updated_ages)

[61 51 37 30 43 61 41 45 33 33]


In [ ]:
#Using NumPy, calculated the total salary expense and the difference between the maximum and minimum salary. Printed both results
total_salary = np.sum(salaries)
salary_diff = np.max(salaries) - np.min(salaries)
print("Total Salary Expense:", total_salary)
print("Difference:", salary_diff)

Total Salary Expense: 574469
Difference between Max and Min Salary: 58966


Q6. Load the employees.csv file into a Pandas DataFrame. Display the first 5 rows, and check basic info using info() and summary statistics using describe().


In [ ]:
#Loaded the employees.csv file into a Pandas DataFrame. Displayed the first 5 rows, and checked basic info and summary statistics
import pandas as pd
df = pd.read_csv('employees.csv')
print(df.head())
print(df.info())
print(df.describe())


   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes
None
             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000


In [ ]:
#Displayed  the id, age, and salary columns. Then showed the last 3 rows
selected_columns = df[['id', 'age', 'salary']]
print(selected_columns)
print(selected_columns.tail(3))

   id  age  salary
0   1   56   77191
1   2   46   74131
2   3   32   46023
3   4   25   71090
4   5   38   31685
5   6   56   30769
6   7   36   89735
7   8   40   86101
8   9   28   32433
9  10   28   35311
   id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311


In [ ]:
#Filtered the DataFrame to show only employees who work in the IT department
it_employees = df[df['dept'] == 'IT']
print(it_employees)
print("total no. of IT employees: ",len(it_employees))


   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT
3


Q9. Sort the DataFrame by salary in descending order and display the top 3 highest-paid employees along with their department and age.


In [ ]:
# Sorted the DataFrame by salary in descending order and displayed the top 3 highest-paid employees along with their department and age
sorted_df = df.sort_values(by='salary', ascending=False)
top_3 = sorted_df[['id', 'dept', 'age', 'salary']].head(3)
print(top_3)


   id     dept  age  salary
6   7  Finance   36   89735
7   8       IT   40   86101
0   1       HR   56   77191


Q10. Replace all salary values greater than 80000 with 80000 using loc. Then calculate and print the new average salary of all employees after replacement.


In [ ]:
#Replaced all salary values greater than 80000 with 80000
#calculated and printed the new average salary of all employees after replacement
df.loc[df['salary'] > 80000, 'salary'] = 80000
average_salary = df['salary'].mean()
print("New average salary", average_salary)

New average salary 55863.3
